"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  ArrowRight,
  ShieldCheck,
  FileText,
  ScrollText,
  Scan,
  LayoutDashboard,
  Copy,
  Download,
  RefreshCw,
  Info,
  CheckCircle2,
  Clock,
  Minus,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type RegulationStatus = "Matched" | "Partially Matched" | "Informational";
type HistoryStatus = "Completed" | "Pending" | "Not Yet";

// ─── Data ─────────────────────────────────────────────────────────────────────

const documentInfo = {
  aiSystem: "Resume Screening AI",
  applicableLaw: "Illinois HB3773",
  generatedBy: "ComplyTrace AI",
  lastUpdated: "Today",
  status: "Draft" as const,
};

const disclosureText = `AI USAGE DISCLOSURE

Effective Date: June 25, 2026
Organization: [Your Organization Name]
AI System: Resume Screening AI

─────────────────────────────────────────────────────────────────────────────

1. NOTICE OF AUTOMATED DECISION-MAKING

Our organization uses artificial intelligence and automated decision-making tools to assist in the evaluation and ranking of job applications. This notice is provided in accordance with applicable AI transparency regulations, including Illinois HB3773, Colorado SB205, and New York City Local Law 144.

2. PURPOSE AND SCOPE

The AI system described in this disclosure is used exclusively to assist qualified human personnel in reviewing job applications. The system analyzes submitted materials and produces a ranked output for internal use. No employment decision is made solely by the automated system.

3. HUMAN OVERSIGHT

AI recommendations are reviewed by qualified human personnel before any employment decisions are finalized. Applicants who advance or are declined in the hiring process are evaluated through a process that includes human judgment.

4. APPLICANT RIGHTS

You have the right to:

  (a) Request information about the use of automated decision-making in the evaluation of your application.

  (b) Request that a qualified human review your application independent of the AI system's output.

  (c) Submit a written inquiry to our compliance team regarding the specific factors considered in any automated evaluation.

5. DATA HANDLING

All applicant data processed by the AI system is handled in accordance with applicable data protection laws. Data is not used to train or improve third-party AI models without explicit consent.

6. BIAS MITIGATION

Our organization conducts regular audits of the AI system to identify and mitigate potential bias in employment decisions. Audit results are available upon written request where required by applicable regulations.

7. CONTACT INFORMATION

To exercise your rights under this disclosure or to submit a compliance inquiry, contact our Privacy and Compliance team at:

  compliance@[yourorganization.com]
  [Your Organization Name]
  [Street Address]
  [City, State, ZIP]

─────────────────────────────────────────────────────────────────────────────

This disclosure has been generated by ComplyTrace AI based on currently applicable AI regulations. It is provided as a starting point for compliance and should be reviewed by qualified legal or compliance personnel before official use.

Document ID: CT-2026-0625-RSA-001
Generated: June 25, 2026`;

const referencedRegulations: {
  lawName: string;
  state: string;
  whyIncluded: string;
  status: RegulationStatus;
}[] = [
  {
    lawName: "Illinois HB3773",
    state: "Illinois",
    whyIncluded: "Requires applicant notification when AI is used in employment-related decisions, including resume screening.",
    status: "Matched",
  },
  {
    lawName: "Colorado SB205",
    state: "Colorado",
    whyIncluded: "Governs high-risk AI systems used in consequential employment decisions. Resume ranking qualifies as high-risk.",
    status: "Matched",
  },
  {
    lawName: "California AB2602",
    state: "California",
    whyIncluded: "Addresses automated decision tools in employment. Partial match due to ranking vs. final decision distinction.",
    status: "Partially Matched",
  },
  {
    lawName: "NYC Local Law 144",
    state: "New York",
    whyIncluded: "Requires annual bias audits and candidate notification for automated employment decision tools.",
    status: "Informational",
  },
];

const documentHistory: {
  label: string;
  note: string;
  status: HistoryStatus;
  icon: typeof CheckCircle2;
}[] = [
  {
    label: "Generated",
    note: "Today",
    status: "Completed",
    icon: CheckCircle2,
  },
  {
    label: "Reviewed",
    note: "Pending",
    status: "Pending",
    icon: Clock,
  },
  {
    label: "Downloaded",
    note: "Not yet",
    status: "Not Yet",
    icon: Minus,
  },
];

const nextActions = [
  {
    label: "View Audit Log",
    description: "Inspect the tamper-evident record of all AI compliance actions.",
    icon: ScrollText,
    href: "/audit",
  },
  {
    label: "Back to Dashboard",
    description: "Return to your compliance overview and state coverage.",
    icon: LayoutDashboard,
    href: "/dashboard",
  },
  {
    label: "Analyze Another AI System",
    description: "Add and analyze another AI use case in your organization.",
    icon: Scan,
    href: "/use-cases",
  },
  {
    label: "Generate Another Document",
    description: "Run law matching again or select a different regulation.",
    icon: FileText,
    href: "/law-matches",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function RegulationStatusBadge({ status }: { status: RegulationStatus }) {
  const map: Record<RegulationStatus, string> = {
    Matched: "border-foreground/25 text-foreground bg-foreground/10",
    "Partially Matched": "border-foreground/20 text-foreground bg-foreground/[0.06]",
    Informational: "border-foreground/15 text-muted-foreground bg-foreground/5",
  };
  const dot: Record<RegulationStatus, string> = {
    Matched: "bg-foreground",
    "Partially Matched": "bg-foreground/50",
    Informational: "bg-foreground/30",
  };
  return (
    <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 border text-xs font-mono shrink-0 ${map[status]}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${dot[status]}`} />
      {status}
    </span>
  );
}

function HistoryStatusIndicator({ status }: { status: HistoryStatus }) {
  if (status === "Completed") {
    return <CheckCircle2 className="w-4 h-4 text-foreground/70 shrink-0" />;
  }
  if (status === "Pending") {
    return <Clock className="w-4 h-4 text-foreground/40 shrink-0" />;
  }
  return <Minus className="w-4 h-4 text-foreground/20 shrink-0" />;
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function DisclosuresPage() {
  const [isVisible, setIsVisible] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isRegeneratingAnim, setIsRegeneratingAnim] = useState(false);
  const [expandedRegs, setExpandedRegs] = useState<Record<string, boolean>>({});

  useEffect(() => {
    setIsVisible(true);
  }, []);

  function handleCopy() {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleRegenerate() {
    setIsRegeneratingAnim(true);
    setTimeout(() => setIsRegeneratingAnim(false), 1200);
  }

  function toggleReg(lawName: string) {
    setExpandedRegs((prev) => ({ ...prev, [lawName]: !prev[lawName] }));
  }

  return (
    <div className="relative min-h-screen bg-background noise-overlay overflow-x-hidden">
      {/* Grid lines */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none opacity-30">
        {[...Array(8)].map((_, i) => (
          <div
            key={`h-${i}`}
            className="absolute h-px bg-foreground/10"
            style={{ top: `${12.5 * (i + 1)}%`, left: 0, right: 0 }}
          />
        ))}
        {[...Array(12)].map((_, i) => (
          <div
            key={`v-${i}`}
            className="absolute w-px bg-foreground/10"
            style={{ left: `${8.33 * (i + 1)}%`, top: 0, bottom: 0 }}
          />
        ))}
      </div>

      {/* Top bar */}
      <header className="relative z-10 px-6 lg:px-12 h-16 flex items-center justify-between border-b border-foreground/10">
        <Link href="/" className="flex items-center gap-2">
          <span className="font-display text-xl tracking-tight">ComplyTrace</span>
          <span className="text-muted-foreground font-mono text-xs mt-0.5">AI</span>
        </Link>
        <div className="flex items-center gap-4">
          <Link
            href="/law-matches"
            className="text-xs font-mono text-muted-foreground hover:text-foreground transition-colors duration-150"
          >
            &larr; Law Matches
          </Link>
          <ShieldCheck className="w-4 h-4 text-muted-foreground" />
          <span className="text-xs font-mono text-muted-foreground hidden sm:inline">SOC 2 Compliant</span>
        </div>
      </header>

      {/* Main */}
      <main className="relative z-10 max-w-[1400px] mx-auto px-6 lg:px-12 py-12 lg:py-16">

        {/* ── Page Header ── */}
        <div
          className={`flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6 mb-12 transition-all duration-700 ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
          }`}
        >
          <div>
            <span className="inline-flex items-center gap-3 text-sm font-mono text-muted-foreground mb-4">
              <span className="w-8 h-px bg-foreground/30" />
              Disclosures
            </span>
            <h1 className="text-4xl lg:text-5xl font-display tracking-tight mb-3">
              Compliance Document Generator
            </h1>
            <p className="text-base text-muted-foreground max-w-xl leading-relaxed">
              Generate professional compliance documents based on your applicable AI regulations.
            </p>
          </div>
          <div className="flex flex-col items-start sm:items-end gap-2 shrink-0">
            <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
              Document Status
            </span>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 border border-foreground/20 text-sm font-mono text-foreground bg-foreground/[0.06]">
              <span className="w-1.5 h-1.5 rounded-full bg-foreground/50" />
              {documentInfo.status}
            </span>
          </div>
        </div>

        {/* ── Document Info Card ── */}
        <section
          aria-label="Document information"
          className={`grid grid-cols-2 lg:grid-cols-5 gap-px border border-foreground/10 mb-12 transition-all duration-700 delay-100 ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
          }`}
        >
          {[
            { label: "AI System", value: documentInfo.aiSystem },
            { label: "Applicable Law", value: documentInfo.applicableLaw },
            { label: "Generated By", value: documentInfo.generatedBy },
            { label: "Last Updated", value: documentInfo.lastUpdated },
            { label: "Document Status", value: documentInfo.status },
          ].map((item) => (
            <div
              key={item.label}
              className="bg-background px-6 py-5 flex flex-col gap-2 border-r border-foreground/10 last:border-r-0"
            >
              <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
                {item.label}
              </span>
              <span className="text-sm font-sans font-medium text-foreground leading-snug">
                {item.value}
              </span>
            </div>
          ))}
        </section>

        {/* ── Two-column body ── */}
        <div className="grid lg:grid-cols-[1fr_340px] gap-8">

          {/* LEFT — Editor + Regulations + Next Steps */}
          <div className="flex flex-col gap-12">

            {/* ── Document Editor ── */}
            <section
              aria-label="Document editor"
              className={`transition-all duration-700 delay-150 ${
                isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              <div className="flex items-center gap-3 mb-5">
                <span className="w-8 h-px bg-foreground/30" />
                <h2 className="text-sm font-mono text-muted-foreground uppercase tracking-widest">
                  Document Editor
                </h2>
              </div>

              {/* Action bar */}
              <div className="flex flex-wrap items-center gap-2 mb-4">
                <Button
                  size="sm"
                  variant="outline"
                  className="h-9 px-4 text-xs font-mono border-foreground/15 hover:bg-foreground/5 rounded-none gap-2"
                  onClick={handleCopy}
                >
                  <Copy className="w-3.5 h-3.5" />
                  {copied ? "Copied" : "Copy"}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-9 px-4 text-xs font-mono border-foreground/15 hover:bg-foreground/5 rounded-none gap-2"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download PDF
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-9 px-4 text-xs font-mono border-foreground/15 hover:bg-foreground/5 rounded-none gap-2"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download DOCX
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-9 px-4 text-xs font-mono border-foreground/15 hover:bg-foreground/5 rounded-none gap-2 ml-auto"
                  onClick={handleRegenerate}
                >
                  <RefreshCw className={`w-3.5 h-3.5 transition-transform duration-500 ${isRegeneratingAnim ? "animate-spin" : ""}`} />
                  Regenerate
                </Button>
              </div>

              {/* Editor area */}
              <div className="border border-foreground/15 relative">
                {/* Editor chrome */}
                <div className="flex items-center justify-between px-4 py-2.5 border-b border-foreground/10 bg-foreground/[0.02]">
                  <div className="flex items-center gap-2">
                    <FileText className="w-3.5 h-3.5 text-muted-foreground" />
                    <span className="text-xs font-mono text-muted-foreground">
                      AI_Usage_Disclosure_ResumeScreening_2026.txt
                    </span>
                  </div>
                  <span className="text-xs font-mono text-muted-foreground">Editable</span>
                </div>
                {/* Text area */}
                <textarea
                  className="w-full bg-background text-sm font-mono text-foreground leading-relaxed p-6 resize-none focus:outline-none min-h-[560px] placeholder:text-muted-foreground"
                  defaultValue={disclosureText}
                  spellCheck={false}
                  aria-label="Compliance disclosure document"
                />
              </div>

              <p className="text-xs font-mono text-muted-foreground mt-3">
                This document is editable. Review and modify the content before downloading or distributing.
              </p>
            </section>

            {/* ── Referenced Regulations ── */}
            <section
              aria-label="Referenced regulations"
              className={`transition-all duration-700 delay-200 ${
                isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              <div className="flex items-center gap-3 mb-5">
                <span className="w-8 h-px bg-foreground/30" />
                <h2 className="text-sm font-mono text-muted-foreground uppercase tracking-widest">
                  Referenced Regulations
                </h2>
                <span className="inline-flex items-center px-2 py-0.5 border border-foreground/15 text-xs font-mono text-muted-foreground">
                  {referencedRegulations.length}
                </span>
              </div>

              <div className="flex flex-col gap-px border border-foreground/10">
                {referencedRegulations.map((reg) => {
                  const isExpanded = expandedRegs[reg.lawName] ?? false;
                  return (
                    <div key={reg.lawName} className="bg-background border-b border-foreground/10 last:border-b-0">
                      <button
                        type="button"
                        onClick={() => toggleReg(reg.lawName)}
                        className="w-full flex items-center gap-4 px-6 py-4 hover:bg-foreground/[0.02] transition-colors duration-150 text-left"
                        aria-expanded={isExpanded}
                      >
                        <div className="flex-1 min-w-0 flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                          <div className="flex items-center gap-3 min-w-0">
                            <span className="text-sm font-sans font-medium text-foreground shrink-0">
                              {reg.lawName}
                            </span>
                            <span className="text-xs font-mono text-muted-foreground shrink-0">
                              {reg.state}
                            </span>
                          </div>
                          <RegulationStatusBadge status={reg.status} />
                        </div>
                        {isExpanded ? (
                          <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />
                        )}
                      </button>
                      {isExpanded && (
                        <div className="px-6 pb-5 border-t border-foreground/10">
                          <p className="text-xs font-mono text-muted-foreground leading-relaxed mt-4">
                            {reg.whyIncluded}
                          </p>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </section>

            {/* ── Document History ── */}
            <section
              aria-label="Document history"
              className={`transition-all duration-700 delay-250 ${
                isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              <div className="flex items-center gap-3 mb-5">
                <span className="w-8 h-px bg-foreground/30" />
                <h2 className="text-sm font-mono text-muted-foreground uppercase tracking-widest">
                  Document History
                </h2>
              </div>

              <div className="border border-foreground/10">
                {documentHistory.map((item, i) => (
                  <div
                    key={item.label}
                    className={`flex items-center gap-5 px-6 py-5 ${
                      i < documentHistory.length - 1 ? "border-b border-foreground/10" : ""
                    }`}
                  >
                    {/* Timeline connector */}
                    <div className="flex flex-col items-center gap-1 shrink-0">
                      <HistoryStatusIndicator status={item.status} />
                      {i < documentHistory.length - 1 && (
                        <div className="w-px h-4 bg-foreground/10" />
                      )}
                    </div>
                    <div className="flex-1 flex items-center justify-between gap-4">
                      <div>
                        <p className="text-sm font-sans font-medium text-foreground mb-0.5">
                          {item.label}
                        </p>
                        <p className="text-xs font-mono text-muted-foreground">{item.note}</p>
                      </div>
                      <span
                        className={`text-xs font-mono shrink-0 ${
                          item.status === "Completed"
                            ? "text-foreground"
                            : "text-muted-foreground"
                        }`}
                      >
                        {item.status}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* ── Recommended Next Steps ── */}
            <section
              aria-label="Recommended next steps"
              className={`transition-all duration-700 delay-300 ${
                isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
              }`}
            >
              <div className="flex items-center gap-3 mb-5">
                <span className="w-8 h-px bg-foreground/30" />
                <h2 className="text-sm font-mono text-muted-foreground uppercase tracking-widest">
                  Recommended Next Steps
                </h2>
              </div>

              <div className="grid sm:grid-cols-2 gap-px border border-foreground/10">
                {nextActions.map((action) => (
                  <Link
                    key={action.href}
                    href={action.href}
                    className="group bg-background flex items-start gap-4 px-6 py-5 hover:bg-foreground/[0.03] transition-colors duration-150 border-r border-b border-foreground/10 last:border-r-0"
                  >
                    <div className="w-8 h-8 border border-foreground/15 flex items-center justify-center shrink-0 mt-0.5 group-hover:border-foreground/40 transition-colors duration-150">
                      <action.icon className="w-4 h-4 text-foreground/60 group-hover:text-foreground transition-colors duration-150" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-sans font-medium text-foreground mb-1">{action.label}</p>
                      <p className="text-xs font-mono text-muted-foreground leading-relaxed">{action.description}</p>
                    </div>
                    <ArrowRight className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5 transition-transform duration-200 group-hover:translate-x-1" />
                  </Link>
                ))}
              </div>
            </section>
          </div>

          {/* RIGHT — Sidebar */}
          <aside
            className={`flex flex-col gap-6 transition-all duration-700 delay-200 ${
              isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
            }`}
          >
            {/* About AI Generated Documents */}
            <div className="border border-foreground/10 p-6">
              <div className="flex items-center gap-3 mb-4">
                <Info className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
                  About AI Generated Documents
                </span>
              </div>
              <p className="text-sm font-sans text-muted-foreground leading-relaxed">
                These documents are generated from your AI system descriptions and matched regulations. They provide a starting point for compliance and should be reviewed by your organization before official use.
              </p>
              <div className="mt-5 pt-4 border-t border-foreground/10 flex flex-col gap-3">
                {[
                  "Not a substitute for legal advice",
                  "Reflects currently matched regulations",
                  "Edit before distributing externally",
                  "Audit log entry created on generation",
                ].map((note) => (
                  <div key={note} className="flex items-start gap-2.5">
                    <div className="w-1 h-1 rounded-full bg-foreground/30 shrink-0 mt-1.5" />
                    <span className="text-xs font-mono text-muted-foreground leading-relaxed">{note}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Document summary */}
            <div className="border border-foreground/10 p-6">
              <div className="flex items-center gap-3 mb-5">
                <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
                  Document Summary
                </span>
              </div>
              <div className="flex flex-col gap-4">
                {[
                  { label: "Regulations cited", value: "4" },
                  { label: "Required actions", value: "9" },
                  { label: "Jurisdictions covered", value: "4" },
                  { label: "Sections", value: "7" },
                ].map((item) => (
                  <div key={item.label} className="flex items-center justify-between">
                    <span className="text-xs font-mono text-muted-foreground">{item.label}</span>
                    <span className="text-2xl font-display tracking-tight">{item.value}</span>
                  </div>
                ))}
              </div>
              <div className="mt-5 pt-4 border-t border-foreground/10 flex flex-col gap-2">
                <Button
                  size="sm"
                  className="w-full bg-foreground hover:bg-foreground/90 text-background h-10 text-xs rounded-full group gap-2"
                  onClick={handleCopy}
                >
                  <Copy className="w-3.5 h-3.5" />
                  {copied ? "Copied to clipboard" : "Copy Document"}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="w-full h-10 text-xs font-mono border-foreground/15 hover:bg-foreground/5 rounded-full gap-2"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download PDF
                </Button>
              </div>
            </div>

            {/* Compliance checklist */}
            <div className="border border-foreground/10 p-6">
              <div className="flex items-center gap-3 mb-5">
                <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
                  Before You Share
                </span>
              </div>
              <div className="flex flex-col gap-3">
                {[
                  { label: "Replace placeholder org name", done: false },
                  { label: "Verify contact email address", done: false },
                  { label: "Confirm effective date is correct", done: false },
                  { label: "Legal team review completed", done: false },
                  { label: "Upload to document archive", done: false },
                ].map((item) => (
                  <div key={item.label} className="flex items-center gap-3">
                    <div
                      className={`w-3.5 h-3.5 border shrink-0 flex items-center justify-center ${
                        item.done
                          ? "border-foreground/40 bg-foreground/10"
                          : "border-foreground/20"
                      }`}
                    />
                    <span className="text-xs font-mono text-muted-foreground leading-relaxed">
                      {item.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Audit note */}
            <div className="border border-foreground/10 p-6">
              <div className="flex items-center gap-3 mb-4">
                <ShieldCheck className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs font-mono text-muted-foreground uppercase tracking-widest">
                  Audit Trail
                </span>
              </div>
              <p className="text-sm font-sans text-muted-foreground leading-relaxed mb-5">
                This document generation has been recorded in your tamper-evident audit log with a cryptographic signature.
              </p>
              <Link
                href="/audit"
                className="inline-flex items-center gap-2 text-xs font-mono text-foreground hover:text-muted-foreground transition-colors duration-150 group"
              >
                View audit log
                <ArrowRight className="w-3 h-3 transition-transform duration-200 group-hover:translate-x-0.5" />
              </Link>
            </div>
          </aside>
        </div>

        {/* ── Footer note ── */}
        <div
          className={`flex items-center gap-3 pt-8 mt-12 border-t border-foreground/10 transition-all duration-700 delay-400 ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
          }`}
        >
          <ShieldCheck className="w-4 h-4 text-muted-foreground shrink-0" />
          <p className="text-xs font-mono text-muted-foreground">
            All compliance documents are stored with cryptographic signatures. This generation event has been recorded in your immutable audit log.
          </p>
        </div>
      </main>
    </div>
  );
}
